services:
  - type: web
    name: telegram-crypto-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: BLOCKCYPHER_TOKEN
        fromSecret: BLOCKCYPHER_TOKEN
      - key: LITECOIN_API_KEY
        fromSecret: LITECOIN_API_KEY
      - key: ADMIN_USER_ID
        fromSecret: ADMIN_USER_ID
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_PORT
        fromSecret: DB_PORT
      - key: DB_NAME
        fromSecret: DB_NAME
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
